spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/liteblog
    username: nijikawa
    password: nijikawa
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
server:
  port: 9000
shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379
nijikawa:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
    expire: 604800
    header: Authorization