spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nocobase
    username: nocobase
    password: nocobase
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
server:
  port: 9000